name: Release

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        customer: ['TestEnv', 'DemoEstate']
      fail-fast: true
      max-parallel: 1  
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest
    environment:
      name: ${{ matrix.customer }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      #- name: Get the version
      #  id: get_version
      #  run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set ConnectionStringVar
        run: echo ::set-env name=ConnString::${{ matrix.customer }}ConnectionString

      - name: Test
        run: echo $ConnString     
      #- name: Install SQL Tools
      #  uses: potatoqualitee/mssqlsuite@v1.7
      #  with:
      #    install: sqlclient

      #- name: Deploy view changes
      #  run: pwsh \DataModel\RUNSQL.ps1 -ConnectionString $STEPVAR -SQLFilePath "DataModel\"           
                
    
    

      

    